### ISSUE TITLE
Offset property with node.js

### ISSUE THREAD

**Issue by theweiweiway** [Airtable/airtable.js#102]
Hi, I would like to use the offset property to paginate through records with Node.js. I understand it exists for curl, but could it be implemented for Node.js as well? 

I think this has been asked before here: 
https://github.com/Airtable/airtable.js/issues/20
https://community.airtable.com/t/pagination-implementation/550/9

**Comment by EvanHahn** [comment]
What is your use case? I've read your forum posts and don't think I understand.

**Comment by theweiweiway** [comment]
Thanks for comment, sorry if I was unclear.

For example, I have 500 records in a table. I want to grab the first 100 records to populate the front-end of my website. Then, when a user of my website clicks "load more", I want to grab the next 100 records.

I understand this is possible by loading all 500 records up front, and then saving them all in the state of my front-end. However, what if I had 5000 records or 10,000 records? Grabbing all of the records in one go doesn't seem like a very good solution because there would be a long loading time. Also, what is the point of grabbing all of the records if the user doesn't keep clicking "load more" to view them all? 

By having an offset property, I could only grab the first 100 records. Then, when the user clicks "load more" I could then grab ONLY the next 100 records. So I only have to grab 100 records at a time. This would allow for scalability of people using the Airtable platform. 

From the API docs, we already have access to the offset property in curl. However, would it be possible to provide it for Node.js as well? 

Thanks Evan

**Comment by EvanHahn** [comment]
That makes sense to me.

You should be able to accomplish this by calling `fetchNextPage` only when needed. You can fetch the first page, and then call `fetchNextPage` only when the user requests it.

If that approach doesn't work for you for some reason, you should be able to make HTTP requests to our API directly for a more customized use case, allowing you to sidestep any of Airtable.js you don't like.

As an aside: Airtable is not intended to be a backend hosting service like Parse or Firebase. Our API is useful for extending Airtable's existing functionality (e.g. setting up a custom sync integration with a calendar app), but is not meant to provide a backend to a web app. Not sure if that's what you're doing, but it sounds a little like it, and you might be running up against challenges that Airtable isn't meant for.

**Comment by theweiweiway** [comment]
got it Evan, thanks a lot for the help and response

**Comment by EvanHahn** [comment]
Glad I could help! Feel free to open a new issue or post in the forums if you have other issues.

**Comment by RonnenPodolsky** [comment]
@EvanHahn "You should be able to accomplish this by calling fetchNextPage only when needed. You can fetch the first page, and then call fetchNextPage only when the user requests it."

How? :)

**Comment by EvanHahn** [comment]
@RonnenPodolsky I don't work at Airtable any more so I can't help you, sorry!
