### ISSUE TITLE
consider got

### ISSUE THREAD

**Issue by kyeotic** [Airtable/airtable.js#108]
airtable.js would be very useful in serverless environments, which are very sensitive to package size. There are two different request libraries in the dependencies of this package, `request` and `xhr`. Please consider [got](https://github.com/sindresorhus/got) as a smaller alternative (for node) and [ky](https://github.com/sindresorhus/ky) for browsers.

**Comment by EvanHahn** [comment]
Thanks for reporting—we'll consider this.

For what it's worth, `node-fetch` also looks pretty compelling because it's even smaller than `got` and it's (theoretically) compatible with browsers' `fetch`. What do you think?

**Comment by tyrsius** [comment]
If you can make it work, the smaller the better. I assumed you were using `request` for one of its advanced features, like retries, which `node-fetch` didn't have.

**Comment by EvanHahn** [comment]
Sorry for the late response—this is something we'll consider (but may not get to soon because we're a small team).

**Comment by kyeotic** [comment]
If this is something you guys are open too I would be happy to contribute and submit a PR.

**Comment by kyeotic** [comment]
@EvanHahn So, I might have gone a little overboard, but this was really fun for me to make.

I re-implemented this client with a more async/await focused style. I haven't published it yet, but I am going to convert my personal project soon to give it a shot. If this is something you guys are interested in using let me know.

https://github.com/kyeotic/airtable

**Comment by EvanHahn** [comment]
This is cool! I especially dig the iterator behavior ([I'm a fan of iterables on the side](https://github.com/EvanHahn/iterpal)). Let us know how it goes with your personal project.

I don't expect that we'll stop supporting Airtable.js, but we may look to your work as we design new versions.

**Comment by kyeotic** [comment]
I'm glad you like it! :grinning: 

Since I started this issue considering size, I figured I would share the bundlesize (as reported by [size-limit](https://github.com/ai/size-limit)) of the published `0.1.0`

```
  Package size: 5.61 KB with all dependencies, minified and gzipped
  Loading time: 113 ms  on slow 3G
  Running time: 118 ms  on Snapdragon 410
  Total time:   230 ms
```

**Comment by EvanHahn** [comment]
It seems like your library has helped solve this issue. Do you mind if we close it? (No worries if not!)

**Comment by EvanHahn** [comment]
Thanks! Feel free to open a new issue if you have any other questions.
