### ISSUE TITLE
Help with Authentication when proxying through CDN

### ISSUE THREAD

**Issue by gtalarico** [Airtable/airtable.js#116]
### Overview

I recently wrote an article on using Airtable (Airtable.js + lambda) as a content backend.
https://medium.com/@gtalarico/using-airtable-as-a-content-backend-e373cd0d9974

A few people mentioned the 5 req/sec rate limit could be an issue, so I am trying to add additional details about how one could add a CDN (eg. Cloudfront) to cache the requests and avoid the rate limit.

I created airtable as the origin on cloudfront, and set it up to pass through Authorization headers. I am able to successful use the CDN to proxy/cache the calls

### Request works as expected through curl:

```bash
$ curl -L "https://d2j5hchu5g3uxq.cloudfront.net/v0/appNtnZ99fkL1cByn/entries?maxRecords=100&view=all" \
    -H "authorization: Bearer keyOmitted"

STATUS: 200

{"records":[{"id":"recW0FpRZMaQv5Ble","fields":{"title":"3D 
[... truncated ]
```

### Requests fail when using airtable.js

I then make the exact same request When I make the same call through airtable.js, but I get `AUTHENTICATION_REQUIRED`.

I logged the `options` variable right before airtable.js runs `runAction` and the payload looks good and matches my curl, so I really can't understand why it would fail:

```
// run_action.js
# line 52
console.log(JSON.stringify(options))
request(options, function(error, resp, body) {
[ ... ]
```

#### Outputs:

```
// `options`
{
   "method":"GET",
   "url":"https://d2j5hchu5g3uxq.cloudfront.net/v0/appNtnZ99fkL1cByn/entries?maxRecords=100&view=all",
   "json":true,
   "timeout":300000,
   "headers":{
      "authorization":"Bearer keyOMITTED",
      "x-api-version":"0.1.0",
      "x-airtable-application-id":"appNtnZ99fkL1cByn",
      "User-Agent":"Airtable.js/0.1.0"
   },
   "agentOptions":{
      "rejectUnauthorized":false
   }
}

Response with status 500 in 686 ms.
Error during invocation:  s {
  error: 'AUTHENTICATION_REQUIRED',
  message: 'You should provide valid api key to perform this operation',
  statusCode: 401
}
```

I apologize as this _may_ not be an issue with the lib but I am out of ideas here.
Let me know if you have any insights, otherwise feel free to close it.

Here is section I am adding to the article - I would be happy to add a wiki page or doc so other users can use the same approach to cache the rate limit:

## Article Update:

![image](https://user-images.githubusercontent.com/9513968/59484770-f3ffb100-8e27-11e9-8399-bd76853ea2d3.png)
![image](https://user-images.githubusercontent.com/9513968/59484784-011ca000-8e28-11e9-8b23-3a918f433c4c.png)

**Comment by EvanHahn** [comment]
Hmm, that's a strange one. I'm not super familiar with CloudFront, but as you say, the `curl` request looks the same as the Airtable.js request.

It's not _completely_ the same, though—most significantly, your `curl` invocation seems to be missing the `x-api-version` and `x-airtable-application-id` headers. What happens if you set those in your `curl` request?

**Comment by gtalarico** [comment]
I had tried with the headers too, same result.
I tried adding the user agent as well but also did not work.
```
$ curl -L "https://d2j5hchu5g3uxq.cloudfront.net/v0/appNtnZ99fkL1cByn/entries?maxRecords=100&view=all" \
      -H "authorization: Bearer keyOMITTED \
      -H "x-api-version: 0.1.0" \
      -H "x-airtable-application-id: appNtnZ99fkL1cByn"
```

![Screen Shot 2019-06-30 at 8 07 18 PM](https://user-images.githubusercontent.com/9513968/60408183-ba8eab80-9b72-11e9-8577-d47e9c8969b6.png)

@EvanHahn have you seen any examples or docs on how to put the airtable API behind a CDN?
(w/out a server). 
If we can get this to work, it would be greate to have this  as a documented example of how put an airtable behind a CDN for the use case I listed above.

**Comment by gtalarico** [comment]
Also, wanted to add another quick test. 
From shell, everything works as expected

# Works

```shell
 curl -L "https://d2j5hchu5g3uxq.cloudfront.net/v0/appNtnZ99fkL1cByn/entries?maxRecords=100&view=all" \
      -H "authorization: Bearer $AIRTABLE_API_KEY" \
      -H "x-api-version: 0.1.0" \
      -H "x-airtable-application-id: appNtnZ99fkL1cByn" \
      -H "User-Agent: Airtable.js/0.1.0"
```

# Also Works
```shell
curl -L "https://api.airtable.com/v0/appNtnZ99fkL1cByn/entries?maxRecords=100&view=all" \
      -H "authorization: Bearer $AIRTABLE_API_KEY" \
      -H "x-api-version: 0.1.0" \
      -H "x-airtable-application-id: appNtnZ99fkL1cByn" \
      -H "User-Agent: Airtable.js/0.1.0"

# From lib, only api works

```
const Airtable = require('airtable')
Airtable.configure({
    // endpointUrl: 'https://d2j5hchu5g3uxq.clo/udfront.net',     // <=== DOESNT WORK
    endpointUrl: 'https://api.airtable.com',                                  // <=== WORKS
    apiKey: process.env.AIRTABLE_API_KEY
  })
  const base = Airtable.base('appNtnZ99fkL1cByn')
  const allRecords = []
  base('entries')
    .select({
      view: 'all'
    })
    .eachPage(
      function page(records, fetchNextPage) {
        records.forEach(function(record) {
          console.log(record)
        })
        fetchNextPage()
      },
    ...
```

**Comment by EvanHahn** [comment]
I haven't seen any examples of people putting Airtable behind a CDN—you might be the first I've heard of.

It's strange that this isn't working. What happens when you use the `request` library by itself to make the same request that Airtable.js is making? Does that succeed? If not, can you change anything about the request to make it succeed?

**Comment by syrnick** [comment]
Try adding -v to curl to see what it’s doing. You are passing -L and that’s suspicious.

Another thing to try is overriding Host header to api.airtable.com explicitly in the CloudFront custom origin.

If none of these work, email support@airtable.com

**Comment by gtalarico** [comment]
> Try adding -v to curl to see what it’s doing. You are passing -L and that’s suspicious.

-L Is required because the CDN redirects to fulfill 

```
❯ curl  "https://d2j5hchu5g3uxq.cloudfront.net/v0/appNtnZ99fkL1cByn/entries?maxRecords=100&view=all" \
      -H "authorization: Bearer keyOMITTED" \
      -H "x-api-version: 0.1.0" \
      -H "x-airtable-application-id: appNtnZ99fkL1cByn" \
      -H "User-Agent: Airtable.js/0.1.0"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<h1>301 Moved Permanently</h1>
<p>The requested resource has been assigned a new permanent URI.</p>
<hr/>Powered by Tengine</body>
</html>
```

**Comment by gtalarico** [comment]
After some more tests and tweaking CDN settings I was able to get it to work.
I am not 100% what the change was that fixed it, but I will post the setting here as a reference.

Thank you @EvanHahn and @syrnick  for you help troubleshooting this.

# Distribution Config
![image](https://user-images.githubusercontent.com/9513968/60686243-76462880-9e5c-11e9-9e54-e6cf88ef2493.png)
 
# Behaviour Config
![image](https://user-images.githubusercontent.com/9513968/60686265-91b13380-9e5c-11e9-8424-ddea863dcc3c.png)


# Origin Config
![image](https://user-images.githubusercontent.com/9513968/60686232-6890a300-9e5c-11e9-9db0-31e75b1b74a1.png)

# Netlify Lambda Code

```js
const Airtable = require('airtable')

Airtable.configure({
  // AIRTABLE_API_URL="https://d2j5hchu5g3uxq.cloudfront.net"
  endpointUrl: process.env.AIRTABLE_API_URL,
  apiKey: process.env.AIRTABLE_API_KEY
})
const base = Airtable.base('appNtnZ99fkL1cByn')

exports.handler = function(event, context, callback) {
  const allRecords = []
  base('entries')
    .select({
      maxRecords: 100,
      view: 'all'
    })
    .eachPage(
      function page(records, fetchNextPage) {
        records.forEach(function(record) {
          allRecords.push(record)
        })
        fetchNextPage()
      },
      function done(err) {
        if (err) {
          callback(err)
        } else {
          const body = JSON.stringify({ records: allRecords })
          const response = {
            statusCode: 200,
            body: body,
            headers: {
              'content-type': 'application/json',
              'cache-control': 'Cache-Control: max-age=300, public'
            }
          }
          callback(null, response)
        }
      }
    )
}

```

**Comment by EvanHahn** [comment]
Glad this was fixed!

**Comment by ricricucit** [comment]
@gtalarico I know it's almost an year ago...but do you have any hints for me? ...got stuck here as well...

**Comment by ricricucit** [comment]
ah! magic for me, as well. It started working after some time, and after invalidating all objects.

Not sure, but I think it was only cloudfront needing some time to go up, properly. 
🤔
