### ISSUE TITLE
airtable version not bumped with lodash fix

### ISSUE THREAD

**Issue by jayhjha** [Airtable/airtable.js#126]
A fix was made 4 days ago to update lodash to version 4.17.14 (https://github.com/Airtable/airtable.js/commit/da1c2b67a4ee078a1456c03622487e3f7d03d259) since lodash had a security vulnerability (https://www.npmjs.com/advisories/1065).

However, the version of airtable.js was not bumped, so when I install 0.6.0, `npm audit` gives a `high vulenrability` since the dependency still includes `4.17.11`.

**Comment by jayhjha** [comment]
Any updates on this? It's a blocking issue.
@EvanHahn, you had made the change with lodash. Will you be able to bump the version as well?

**Comment by EvanHahn** [comment]
Apologies—this is now fixed in `airtable@0.7.0`.
