### ISSUE TITLE
Better error message for error "INVALID_MULTIPLE_CHOICE_OPTIONS" when the message is "Insufficient permissions to create new select option" 

### ISSUE THREAD

**Issue by janzheng** [Airtable/airtable.js#138]
I struggled with `INVALID_MULTIPLE_CHOICE_OPTIONS` for a while, trying to figure out why `Typecast: true` wasn't working.

It turns out that the `Insufficient permissions to create new select option` message means that your API account doesn't have enough privileges to add a single select or multiple select option — the user account needs "Creator" access instead of just "Editor" access as apparently adding a new single select option is considered "configuring a field"

It'd be really cool if the message says something in addition like "The account needs 'Creator' access to the base" — that would really help others, I think.

Thanks!

**Comment by EvanHahn** [comment]
While that message would be correct, it might not hold true forever. If some _other_ condition made it impossible to create a new select choice, that message would go out of date (or at least, be partially incorrect).

To invent a contrived example, imagine that we added the ability for someone to lock down editing of a table only to themselves. That would mean that if you and I were both Creator-level collaborators on a base and you locked a table, I couldn't edit your select fields. That would make this message incorrect. Again, this is a contrived example and not something we have plans to do, but I hope it demonstrates my point.

I'm going to close this issue, but let me know if that's wrong and I'm happy to reopen.

**Comment by janzheng** [comment]
That's really interesting — and it's really cool that you're thinking about expanding Airtable in such directions! — down the line, is there work planned to add more detailed error codes into the API in a way that makes it easier to track down the root cause of errors, like the one I ran into, and maybe like the one in your scenario?

Airtable (and its API) is so incredibly powerful, thanks for all the hard work!

**Comment by EvanHahn** [comment]
Improving API error messages is definitely on our radar.

Glad you like the API!!
