### ISSUE TITLE
Securing Access Token

### ISSUE THREAD

**Issue by stritti** [Airtable/airtable.js#14]
How could I secure the Access Token in a Website created for example with React or Angular completly client side?

I think, it would be a cool thing to have e.g. a PHP-Proxy-Class in addition to reroute the calls for specific app. but then the endpoints should be customizable in airtable.js

**Comment by benoror** [comment]
My approach was to create a proxy using Express.js, you can check out my solution at: https://medium.com/the-backlog-by-nimbo-x/creating-a-serverless-web-app-with-node-js-ember-js-and-paas-services-hyperdev-surge-sh-8e3ebe263a76#.fwwl6zq0v

**Comment by kasrak** [comment]
There isn't a way to do it completely client-side, so you'll need to proxy the requests through a server on your end as @benoror mentioned.

This will also help avoid hitting the rate limit of 5 requests per second, since your proxy can cache reads.

**Comment by syrnick** [comment]
@stritti we have an example proxy: https://github.com/Airtable/airtable_api_proxy . It's not exactly an Airtable API proxy, but a 

Airtable.js had proxy support from day 1: https://github.com/Airtable/airtable.js#configuration . It's handy for all sorts of things.

**Comment by stritti** [comment]
wow, man thanks for your input. This will help me a lot. It is my very first 100% client-only app :)
