### ISSUE TITLE
unable to find how to deal with  [] in the filterByFormula

### ISSUE THREAD

**Issue by sinsunsan** [Airtable/airtable.js#15]
I have been reading your api doc since an hour and tried  multiple thing in postman. 
I cannot find all query that imply array 
like 
https://api.airtable.com/v0/appD26Y6hJLSadC6d/projects?fields=["title","buildYear"]
Where I want to have the list with only the 2 listed fields
fields=["title","buildYear"]

And a query on a relation field 
https://api.airtable.com/v0/appD26Y6hJLSadC6d/projects?architect=["recpxHgMoiA5Dh9i7"]
Where recpxHgMoiA5Dh9i7 is the id of an architect in another table that projects but related thanks to the architect column. 

The doc of airtable.js is very limited, you should improve it if  you want to have more usage of which api that seems well built. 

I've written my personal doc in a more partical format to quickly get success with my queries :) 
https://github.com/sinsunsan/archiref_wiki/wiki/airtable

**Comment by kasrak** [comment]
The parameters need to be URL encoded. You can use this to see what the parameters should look like after URL encoding: https://codepen.io/airtable/full/rLKkYB

Thanks for your feedback, we'll work on improving the docs :)

**Comment by sinsunsan** [comment]
Ok thanks @kasrak  for your codepen, I will reference it in my doc too. 

But any way even with my url encoded
https://api.airtable.com/v0/appD26Y6hJLSadC6d/projects?architect=["recpxHgMoiA5Dh9i7"]
does not work 
Always the same message 
````
{
  "error": {
    "type": "INVALID_FILTER_BY_FORMULA",
    "message": "The formula for filtering records is invalid: please check your formula text."
  }
}
````

You've explained how to deal with fields with spaces with the {} {my field}="toto" or myfield=toto if I have no space in the field name.  
that syntax aspect I have understood. 

But you do not speak about how to deal with arrays 
created by the table relation fields, and also with the attachment field which is specific.
I was thinking 
fieldName=['value', 'value']
Per aps an IN operator ? as it is not really an equal in that case 

The problem of the doc is that it is @purposed to explain the usage for filter Formula with airtable  ui with function field, and the syntax is a bit different in api url query call : no spaces... 

Examples of api call with url uncoded and uncoded would be much more easy to interpret.

**Comment by sinsunsan** [comment]
I've finished to understand, we need to use Linked content primary value 
https://api.airtable.com/v0/appD26Y6hJLSadC6d/projects?fields%5B%5D=title&fields%5B%5D=architect&filterByFormula=architect%3D%22JOD+Architecture%22&pageSize=20

Is there no way to use the record ID ? 

Also I have found a convenient way to use lookup field to output the liked content named along with the id.  (preventing from doing other queries)

**Comment by sinsunsan** [comment]
I think I have some up my mis-conception and this remaining question in this post 
https://sinsunsan.github.io/airtable-api-examples/

**Comment by kasrak** [comment]
If you want to use `filterByFormula` with record IDs in the linked table, you can create a formula in the linked table that is `RECORD_ID()`, then add a lookup to that formula field in the main table. Now when querying the main table you can use `NameOfYourFormulaField="rec123123123"` for `filterByFormula`.

It would look like this after being URL encoded: https://api.airtable.com/v0/YOUR_BASE_ID/YOUR_TABLE_NAME?filterByFormula=NameOfYourFormulaField%3D%22rec123123123%22

**Comment by sinsunsan** [comment]
Thanks.

RECORD_ID() is a very important function actually ! 
Did not stumble upon...
I found strange that you hide the record_id by default, but per aps  to make it simpler for most users. 

Also I have noticed that the result of function fields / columns are not in the api response if we do not set fields specifically.

Does this lookup... and functions add some extra time to the final request ? 
Do we need to care about that to make requests faster ?
Indeed after having understood the lookup function, I have already added 4-5 lookup functions per table. Before that I was doing extra queries mounting  the data front end side. @kasrak

**Comment by sinsunsan** [comment]
Also it is not clear how to use several fields with filterByFormula @kasrak 

typeId=recQV2hPoo3OtZIlg & cityId=recqJSOeMDYYtZBDB
with typeId and cityId 2 lookup fields retrieving a related table id 

But it do not seem to work. 
I am sorry  to ask simple things but there is missing in your docs api use case examples so that it is easy to use it.

https://api.airtable.com/v0/appD26Y6hJLSadC6d/projects?filterByFormula=typeId%3DrecQV2hPoo3OtZIlg%26cityId%3DrecqJSOeMDYYtZBDB&pageSize=20

do not work.

**Comment by sinsunsan** [comment]
The response is 

{
  "error": {
    "type": "INVALID_FILTER_BY_FORMULA",
    "message": "The formula for filtering records is invalid: unknown field names: recqv2hpoo3otzilg, recqjsoemdyytzbdb"
  }
}

**Comment by kasrak** [comment]
Take a look at the formula docs: https://support.airtable.com/hc/en-us/articles/203255215-Formula-field-reference

filterByFormula uses the same system as a formula column Airtable, so one way to test filterByFormula formulas is to create a formula column in the table you're querying. If the formula evaluates to a truthy value, then that record would be included in the response if you used filterByFormula.

In your specific case, you need quote the record IDs and use AND (`&` concatenates strings): `AND(typeId = "recQV2hPoo3OtZIlg", cityId = "recqJSOeMDYYtZBDB")`

**Comment by sinsunsan** [comment]
Thanks i've understood.

Relative to offset and paging, is it only possible to call next page ?
Not possible to call p4, p 22 but only "next page"
So a pager with links to pages is not possible to make ?

**Comment by kasrak** [comment]
Right, it's only possible to fetch pages sequentially right now.

**Comment by sinsunsan** [comment]
Ok never mind, I will then make a instagram style paging system or infinite
loading.
