### ISSUE TITLE
Unly Releases an Open Source Software for Airtable Managed backups

### ISSUE THREAD

**Issue by Vadorequest** [Airtable/airtable.js#156]
As this is most likely to pick developer's interest:
https://community.airtable.com/t/unly-releases-an-open-source-software-for-airtable-managed-backups/26752

> We basically released https://github.com/UnlyEd/airtable-backups-boilerplate which can help you manage backups scheduling and alike! :)

**Comment by EvanHahn** [comment]
Thanks for this! I've shared this with the team, looks cool.

I'm going to close this issue as it isn't a problem with Airtable.js, but thanks again for sharing.
