### ISSUE TITLE
Batched "get by id"

### ISSUE THREAD

**Issue by sseppola** [Airtable/airtable.js#159]
I've seen a lot of requests and mentions of batch create/update (#112), however is there any plans on making a batched "find" api? This would help a lot with rate limiting and enable lots of use-cases.

Currently the best solution I've found is:
```
filterByFormula: `SEARCH(RECORD_ID(), "a1b2c3,a1b2c4,a1b2c5,a1b2c6") != ""`
```
(from https://community.airtable.com/t/most-efficient-way-to-retrieve-specific-records-by-id/23224)

This seems to be quite slow based on the comments, and implementation wise it wouldn't surprise me if it iterates through each id for each record, however if integrated into the api and utilizing an index this would be blazing!

I imagine the `find` function could just accept an array, and you could simply write:
```js
var Airtable = require('airtable');
var base = new Airtable({apiKey: 'YOUR_API_KEY'}).base('apptT07UQOWcGUxAL');

base('People').find(['recW1pBnflSSenKzb'], function(err, records) {
	...
});
```

**Comment by EvanHahn** [comment]
I think there are two pieces to the thing you're asking. First, an API feature that allows users to fetch multiple records by ID. Second, a feature in Airtable.js to use that API.

For the first idea, the API feature: I've noted it, and I think it's a good thought. But to set expectations, I don't think we're going to add this to the API any time soon.

The second idea is something we could consider adding today. But without the API feature above, I'm not sure it's as valuable given that you cite performance as a concern. It would just "compile" to the `filterByFormula` you had above, or something similar.

It's a good idea, but given that you have a workaround and that this isn't a priority, we probably won't add this feature to the API any time soon. I'm going to close this issue for now, but let me know if you'd rather I leave it open.

**Comment by jsep** [comment]
This should be supported in the API, is a basic feature.
