### ISSUE TITLE
What functions are available?

### ISSUE THREAD

**Issue by wraybowling** [Airtable/airtable.js#16]
It's not clear how this npm library can be used. What functions are available on an Airtable object? A code example or two would be great. The API documents how to write a URL to get responses from the API, but I'm assuming that making calls with JavaScript looks different. Maybe I'm wrong, but there's no examples to confirm or debunk that.

**Comment by kasrak** [comment]
If you go to https://airtable.com/api and select the base you're using, you can switch to the "node.js" tab to see code examples using this library.

![screen shot 2016-12-13 at 11 25 17 am](https://cloud.githubusercontent.com/assets/331454/21155437/0da7c960-c127-11e6-8752-0cf28af836c8.png)

**Comment by c-h-** [comment]
How can you programmatically list bases? For example, what do I do if I don't know ahead of time what base to use and need to select it from a list of available bases?
