### ISSUE TITLE
Replacement of 'request' HTTP library.

### ISSUE THREAD

**Issue by FernandoKGA** [Airtable/airtable.js#167]
Hi!
I'd just seen that the [request](https://github.com/request/request) library is now **deprecated**. Which package are you guys considering to replace it with? Or you are going to use the [http API](https://nodejs.org/api/http.html) from Node.js?

**Comment by FernandoKGA** [comment]
Alternative libraries to **request**: https://github.com/request/request/issues/3143

**Comment by minicat** [comment]
The `request` library has been replaced with `node-fetch`: https://github.com/Airtable/airtable.js/pull/191
