### ISSUE TITLE
Related objects are fetched in reversed order

### ISSUE THREAD

**Issue by jilljenn** [Airtable/airtable.js#17]
In the case of a many-to-many relationship, it is possible to drag-and-drop related items in order to change their order.
However, an API call gets the corresponding related objects in reversed order, compared to what is specified in Airtable. Is this normal behavior?

**Comment by kasrak** [comment]
Yep, this is a quirk of the underlying implementation. We can't change it without breaking existing API integrations, so for now, we recommend reversing the list of linked records and attachments if you need to them in the same order as they appear in the UI.
