### ISSUE TITLE
API responses are inconsistent

### ISSUE THREAD

**Issue by cmmartin** [Airtable/airtable.js#174]
I have a base with 1500+ rows. I run a daily job that requests all records. Most days, all records are returned (in 10+ pages). However sometimes it will only return a single page with like 2-3 records.

```javascript
base('base name')
      .select({
        pageSize: 100,
        view: 'Grid view',
      })
      .eachPage(...)
```

Any idea why I would be randomly getting very different responses for the same exact request? Originally, I thought this was a one time bug. But it's been this way for months now. Like 29/30 days in a month everything works great and all rows are returned. But every now and then it only returns like 3 total rows. Any ideas?

**Comment by alexsorokin-at** [comment]
That's unexpected; please contact support@airtable.com ideally with baseId and timestamp of request.

**Comment by cmmartin** [comment]
Thanks. Reached out via email.
