### ISSUE TITLE
List queries with airtable backend and Rest API /  How to do the load more query in the frontend?

### ISSUE THREAD

**Issue by sinsunsan** [Airtable/airtable.js#20]
Hello, 

If I start from  the api documentation to make a list requests to a table.
We figure out that the call is sequential, so there is no way to call page 4 before having fetched page 1, 2, 3...
and the fetchNextPage(); function allow to call next page in the backend. 

```
base('projects').select({
    // Selecting the first 3 records in db:
    maxRecords: 3,
    view: "db"
}).eachPage(function page(records, fetchNextPage) {
    // This function (`page`) will get called for each page of records.

    records.forEach(function(record) {
        console.log('Retrieved', record.get('title'));
    });

    // To fetch the next page of records, call `fetchNextPage`.
    // If there are more records, `page` will get called again.
    // If there are no more records, `done` will get called.
    fetchNextPage();

}, function done(err) {
    if (err) { console.error(err); return; }
});
```
But how can we use that in the front end (using the node.js airtable.js in the backend). 

I make a first query from the front. 
The backend give me only the first 3 results. 
Then which query should I make from the front so that the backend do no need to make again the query for the first 3 results  so that I can get next results ? 

If I do all from the frontend, I can assign the  fetchNextPage(); to the load more button. 

But if I want to use a node.js api ?

Not possible @kasrak

**Comment by sinsunsan** [comment]
For now I make all queries calling fetchNextPage() till it end in the backend to get all results and cache the results for future call in the backend.
But it is not scalable with thousands of records....

**Comment by kasrak** [comment]
Just to make sure I'm understanding correctly, you want to fetch the first page of results on the server, then fetch subsequent pages from the frontend?

That's not directly possible with airtable.js, but you can do it manually by making a `GET` request to the table. The response will include an `offset` field if there are more pages to fetch. You can return this `offset` cursor to the frontend, and when the frontend makes its first request, it can include the `offset` in the request to continue fetching the remaining pages.

See the "Pagination" section of the CURL documentation for more details: https://airtable.com/api

Feel free to re-open if I misunderstood the question!

**Comment by eorroe** [comment]
Please add a way to pass offset value to the `firstPage()` method to allow this

**Comment by CH-ClareMonahan** [comment]
Hi,

I just wanted to see if there had been any discussion about added the `offset` feature to the node.js API? Perhaps I missed it, but it appears that an offset parameter is only available via curl.

I have a service built of the node.js app that filters and pulls from airtable, formats data, and distributes it to various backends. I'm hoping to paginate larger volume requests, while still using filtering features  of node.js API,but not seeing where I can pass an `offset`.

Closest I found was [this conversation](https://community.airtable.com/t/pagination-implementation/550/5), so I am hoping there has been a "strong use case" that it got added or is in the process of being added to the node.js service.

Thanks!!

**Comment by syrnick** [comment]
There's a table.list. It's deprecated in favor of table.select, but we'll review this use case before removing it. table.list calls this https://github.com/Airtable/airtable.js/blob/master/lib/table.js#L114 and you'd pass the limit and offset explicitly.

**Comment by theweiweiway** [comment]
I'm looking to paginate data as well with `offset` in Node.js. This addition to the API would be amazing, since this is probably the biggest problem in terms of scalability with airtable

**Comment by EvanHahn** [comment]
@theweiweiway I saw that you [posted on our forum about this, too](https://community.airtable.com/t/pagination-implementation/550/9). Did you get your answer? If not, could you open a new issue?

**Comment by ChristianBell1995** [comment]
Can we reopen this issue? I would be very grateful for the addition of this feature!
