### ISSUE TITLE
Cannot install v0.9.0 via npm install

### ISSUE THREAD

**Issue by chatii** [Airtable/airtable.js#203]
I run `npm install airtable` to have a nice Airtable, but it doesn't install the latest v0.9.0
(`"airtable": "^0.8.1"`)
Please release v0.9.0 to npm

**Comment by kirillgroshkov** [comment]
Yep, just came here to leave the same question, e.g what are the plans for 0.9.0 release

**Comment by jugglinmike** [comment]
Looks like we're in good shape, now:

    $ npm show airtable dist-tags.latest
    0.9.0

**Comment by chatii** [comment]
@jugglinmike thanks!!
