### ISSUE TITLE
Can I pass a variable to filterByFormula?

### ISSUE THREAD

**Issue by joshhamon** [Airtable/airtable.js#209]
```function aTest(msg){
        console.log("entered test");
        let id = msg.chat.id;
        base('nodes').select({
            view: "Grid view",
            fields: ['uID','name','status'],
            sort:[{field:"name", direction:"asc"}],
            filterByFormula:'(uID=id)'
}).
```

I want sort crud records based on the chat id, how do I pass that to filterByFormula?

**Comment by jeromegout** [comment]
Hi @joshhamon,

I'm definitively not an Airtable expert but I think that what you are looking for is something like:

filterByFormula:`{uID}="${id}"`

Hope it helps

**Comment by joshhamon** [comment]
Thanks! It didn't like that. Part of the issue is filterByFormula wants something in "" 

```
		filterByFormula:"{uID}=\"${id}\""
```

Didn't give me an error but also didn't get any results.

**Comment by agentlewis** [comment]
```
// I am using this in production for a 2 conditional filter: 

filterByFormula: `AND({Field Name With Spaces} = "${myJSVariable}", otherField = "${otherJSVariable}")`

// or one condition (I think this works):

filterByFormula: `{field name} = "${variable}"`
```

Hope that helps :)

Its the kind of snippet that would have been really helpful in the docs...
