### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _SSL_CTX_set_alpn_protos

### ISSUE THREAD

**Issue by mikalyoung** [Airtable/airtable.js#22]
When running the curl

`"https://api.airtable.com/v0/..." -H "Authorization: Bearer ...`,

there is an error:

```
dyld: lazy symbol binding failed: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/.../anaconda/bin/../lib/libcurl.4.dylib
  Expected in: /Users/.../anaconda/bin/../lib/libssl.1.0.0.dylib

dyld: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/.../anaconda/bin/../lib/libcurl.4.dylib
  Expected in: /Users/.../anaconda/bin/../lib/libssl.1.0.0.dylib
```

How do you solve this?

**Comment by syrnick** [comment]
This has nothing to do with airtable.js.

Your anaconda install is breaking CURL. Try removing it from your PATH.

**Comment by ckdotca** [comment]
@mikalyoung, did you find a solution to this? I have the same issue.

**Comment by mab164** [comment]
check ~/.bashrc and ~/.bash_profile and remove the line:
export PATH="/home/sbendl/anaconda2/bin:$PATH"
