### ISSUE TITLE
.all() not answering all the records

### ISSUE THREAD

**Issue by Makio64** [Airtable/airtable.js#249]
It looks like there is a change in the back of Airtable, the request .all() only answer the 20 first records since about a week ago.

Any way to fix it or should I iterate on all page in front?

**Comment by dandv** [comment]
I'm getting 95 records just fine with 0.12.2.

**Comment by DannyMatteson-at** [comment]
Thanks all. The endpoint https://airtable.com/developers/web/api/list-records should return 100 records by default, which is what `.all()` should do. Please take a look to see if the table or view you are calling `.all()` upon is filtered in any way that would lead to fewer records. You can also contact Airtable support for assistance by visiting [Airtable Support](https://support.airtable.com/doc/) and clicking the black chat bubble in the bottom right corner. We will now close this for now.
