### ISSUE TITLE
new CORS issue?

### ISSUE THREAD

**Issue by llaenowyd** [Airtable/airtable.js#251]
Just started getting a CORS error when requesting data from Airtable:

```
Access to fetch at 'https://api.airtable.com/v0/xxxxxxxxxxxxx/Table?view=Grid+view' from origin 'https://app.host.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Just curious what changed?  It might've been a Chrome update.  We're using `airtable-0.10.1`, and have been throughout the project, past 3 months.  I think since this library is making the request on our behalf, I can't do much to add a `no-cors` mode header to the request, and as well I'm not entirely sure that would make it work.

To be clear we already have a CORS proxy (although using it is a cost scaling point), and I'm familiar with the phenomenon, but less sure why the terrain has shifted as of today.

**Comment by llaenowyd** [comment]
I'm really not sure how this was a transient problem, but that's how it appears. 👻 🤔

**Comment by SomeHats** [comment]
We experienced some downtime today that resulted in our API being unavailable for a little while: https://status.airtable.com/incidents/lklr5kgsjz3k

Given the timing of your issue, I'm going to assume that was the cause! It should be resolved now. Thanks for reporting!
