### ISSUE TITLE
API not returning `view` sort order

### ISSUE THREAD

**Issue by janzheng** [Airtable/airtable.js#258]
Hi there,

It seems like something changed overnight and the API isn't respecting the sort order of `views` anymore. Instead, records are being returned by created date, regardless of a view's sort order.

This doesn't affect the visibility of records, and adding a `sort` array still does what it's supposed to.

Thanks!

**Comment by benrazon** [comment]
Thanks for reporting this and apologies for the inconvenience! We had an issue in the underlying API yesterday that has since be resolved.
