### ISSUE TITLE
Unhandled Rejection: TypeError: done is not a function when updating records

### ISSUE THREAD

**Issue by naclcaleb** [Airtable/airtable.js#269]
When I try to update an AirTable record using an ID that doesn't exist in the table, it seems like it tries to use the `done` callback rather than handling it normally as a Promise? Maybe I'm missing something, but even when I have a `catch` (with no throws or anything), it still gives me an `Unhandled Rejection` error. Here's the full message:

```
Unhandled rejection
TypeError: done is not a function
    at /workspace/node_modules/airtable/lib/record.js:49:13
    at /workspace/node_modules/airtable/lib/run_action.js:70:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by naclcaleb** [comment]
I figured it out: I was entering a single record object, rather than an array. Still, it would have been nice if it gave a more intelligent error.

**Comment by jonworek** [comment]
Thanks for sharing your experiences @naclcaleb. This helped me quickly fix what would have otherwise been a frustrating error to figure out. 

I realize this issue has been closed, but if the maintainers are able to do so, I would also suggest throwing a better error message.
