### ISSUE TITLE
Unfriendly docs 

### ISSUE THREAD

**Issue by lucasnantonio** [Airtable/airtable.js#29]
Hi, I'm using airtable and loving every bit of it. 
I'm very new to web development so I don't understand how to use this package to make my calls instead of [request](https://github.com/request/request), the package I've been using so far to connect to Airtable. I'm using node, express and airtable to build a catalogue of things on a website.

I'd appreciate richer instructions on the methods and things I can do by installing this module.
I apologise if this is too basic.

**Comment by kasrak** [comment]
Have you seen the documentation here: https://airtable.com/api

Select your base, then choose "Node.js" to see code examples that are specific to the structure of your base:
<img width="1151" alt="screen shot 2017-05-24 at 9 00 22 am" src="https://cloud.githubusercontent.com/assets/331454/26413024/87cab7b8-405f-11e7-8fcb-b3ff5af35fbc.png">

**Comment by lucasnantonio** [comment]
omg, totally missed the /curl/node/ tabs up there. Thanks a lot!

**Comment by fostimus** [comment]
@kasrak are there update docs? There is no longer a Node tabe

**Comment by kasrak** [comment]
Looks like the tab has been renamed from "node.js" to "JavaScript", but it has the same code examples as before.
