### ISSUE TITLE
API/Docs discrepancy: base.getTable/base.table, table.getField, ...

### ISSUE THREAD

**Issue by tribakzero** [Airtable/airtable.js#290]
Hello there, I'm new to Airtable and trying to get used to it as my current employer is using it as a backend.

Currently building a toy project and wanting to read a field metadata using `table.getField('Field name')` using airtable.js version 0.11.1

I can't find any reference to table.getField neither on the GitHub codebase, issues, but on the official documentation https://www.airtable.com/developers/scripting/api/field. Have it been lately deprecated as I can't find any reference to it being deprecated. Still there are a lot of instances of it on the forums, so I'm very confused.

Can someone help me understand what's going on? Is it by any chance a Plus/Pro API?

**Comment by rbrtmrtn** [comment]
Just a quick +1 on this, but a more generally—I can't seem to find API documentation for Airtable.js. I see a link to the REST API docs in the README, but are there docs for the objects returned by Airtable.js queries (a spec for the `Record` type, for instance?)

Thank you in advance for any help with this!

**Comment by albreyb** [comment]
A couple of things here:

- Getting access to the metadata api is a popular feature request. At this time, our metadata API is closed.
- @tribakzero - to be clear, [the documentation](https://www.airtable.com/developers/scripting/api/field) you referenced to the `table.getfield` function you shared is specifically for the scripting app, not the rest api/airtable.js
- we are going to close this issue in favor of the already open issue @rbrtmrtn referenced [here](https://github.com/Airtable/airtable.js/issues/32).


Albrey, Developer Advocate @ Airtable
