### ISSUE TITLE
Maybe typo in a test key

### ISSUE THREAD

**Issue by tresorama** [Airtable/airtable.js#295]
https://github.com/Airtable/airtable.js/blob/47b5ae542e47e7daebf172ebe0e0099265ab9bac/test/record.test.js#L161

I think there is a typo here.
I think first parameter (string) should start with  ‘put-update' instead of ‘patch-update'.
Maybe it could avoid wasting someone's time in the future.

**Comment by albreyb** [comment]
Thanks for the feedback! We just updated the test. You can see our changes here - #300

**Comment by tresorama** [comment]
Glad to have helped 😀
