### ISSUE TITLE
Airtable.browser.js: Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by CyberStrike** [Airtable/airtable.js#31]
### Problem:

While attempting to use `Airtable.browser.js`using the test in the readme I received.

```javascript
Uncaught ReferenceError: require is not defined
```

### Expected: 

No Errors.

### Steps to Reproduce:

From project root.

```sh
npm install airtable
cd ./node_modules/airtable/test/test_files
python -m SimpleHTTPServer
```
Navigate to test page and view console.

**Comment by kasrak** [comment]
Hm, I don't seem to be able to reproduce this. Did you modify the `index.html` file to have your API key and base ID?

**Comment by kasrak** [comment]
Closing until more details are provided
