### ISSUE TITLE
Add returnFieldsByFieldId option to Retrieve a Record

### ISSUE THREAD

**Issue by MerryOscar** [Airtable/airtable.js#310]
The option `returnFieldsByFieldId` on the **List Records**  endpoint is a great addition for using field ids instead of field names.

It would be great if this option was also supported for the **Retrieve a Record** endpoint.

**Comment by DannyMatteson-at** [comment]
Hi @MerryOscar, this parameter has been added to the **Retrieve a Record** endpoint.

**Comment by MerryOscar** [comment]
Great thanks!
