### ISSUE TITLE
api key deprecation?

### ISSUE THREAD

**Issue by dbvisel** [Airtable/airtable.js#357]
Airtable is sending out ominous messages about API keys being deprecated in favor of personal access tokens. Is this library going to be updated to use them? The most recent email claims that API keys won't work at all after February 1, 2024 – so there is some time, but I would like to get ahead of this change!

**Comment by marks** [comment]
Hey @dbvisel you can pass a personal access token to this library today. The parameter is called `apiKey` but [the README notes](https://github.com/Airtable/airtable.js#configuration):

> # Configuration
> There are three configurable options available:
> * `apiKey` - your secret API token. Visit [/create/tokens](https://airtable.com/create/tokens) to create a personal access token. [OAuth access tokens](https://airtable.com/developers/web/guides/oauth-integrations) can also be used.

Hope this clarifies things for you!

**Comment by dbvisel** [comment]
Oh thanks! I missed that. I'll try out the new method.

**Comment by marks** [comment]
@dbvisel no problem --  but just to be clear, there is no new _code_ method. You can just place a personal access token (looks like `patXXX`) where you used to put your user API key (looks like `keyXXX`)

**Comment by dbvisel** [comment]
I was pleasantly surprised to find it was so easy! Thanks.

**Comment by Anmol-Baranwal** [comment]
@marks 
Is using personal access token affects useSWR? 

I am getting a error in: export const fetcher = (url) => fetch(url).then((res) => res.json());

After converting to personal access token, I have not yet deleted the api key. 
I have tried but the code breaks after using PAT from api key

Do you know the reason behind this?

**Comment by marks** [comment]
> @marks Is using personal access token affects useSWR?
> 
> I am getting a error in: export const fetcher = (url) => fetch(url).then((res) => res.json());
> 
> After converting to personal access token, I have not yet deleted the api key. I have tried but the code breaks after using PAT from api key
> 
> Do you know the reason behind this?

Hi @Anmol-Baranwal - no, but I recommend you try `catch`'ing the error. It should be helpful in debugging the situation. Perhaps you need additional scopes or resources (bases/workspaces) attached to your new PAT. 

The support team at support@airtable.com may be able to help you debug further.

**Comment by Dev1love** [comment]
@Anmol-Baranwal @marks any updates? we have a similar issue. After changing from API key to PAT we keep receiving 403 error. seems like because we have updated to payed subscription last week our API key doesn't work any more. Thanks

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal @marks any updates? we have a similar issue. After changing from API key to PAT we keep receiving 403 error. seems like because we have updated to payed subscription last week our API key doesn't work any more. Thanks

I have yet to contact the team. I will do it soon. (Please do tell me if you get a solution)

**Comment by ruztyA** [comment]
hi, I'm using npm airtable, after I changed the apiKey to personal access token, it kept returning a 403 error. do I miss something in integrating the library with my code? thanks

**Comment by marks** [comment]
@ruztyA @its-a-lisa it's very likely [the PATs](https://airtable.com/developers/web/guides/personal-access-tokens) you have created do not have the proper permissions -- either in terms of scopes (can the token read/write to bases) or resources (specific bases/workspaces/all your bases).

I recommend checking your PAT's scopes and resources first. Nothing in terms of authentication/authorization has changed in the Airtable.js library as best as I can tell.

**Comment by jlong5795** [comment]
I am also having this issue. My PAT has all scopes and access to all bases in all current and future workspaces. It cannot be more privileged.

**Comment by marks** [comment]
@jlong5795 In that case I suggest writing into support@airtable.com for 1:1 help

**Comment by ruztyA** [comment]
My problem is solved! It's because my account does not have the proper permission. I already checked all the scopes but turns out I still do not have permission to write a new row and update a row (my role is as "editor").
So after granting more permissions to my account, it ran smoothly. Thanks, @marks

**Comment by DannyMatteson-at** [comment]
Thank you all for your contributions and discussions. It seems the main concerns have been addressed as airtable.js already supports PATs as needed. If you encounter further issues, please verify your PAT permissions and scopes or contact Airtable support for assistance (Go to https://support.airtable.com/doc/ and click the black chat bubble in bottom right corner). We will now close this issue.
