### ISSUE TITLE
In-browser demo is broken

### ISSUE THREAD

**Issue by daVinciCEB** [Airtable/airtable.js#40]
I'm attempting to see how the in-browser functionality is, but when I do exactly what is written in the README, all I get are errors saying `require is not defined`. When I add require.js to my html file, I'm getting the following error: `Module name "airtable" has not been loaded yet for context: _. Use require([])`.

Is there a step missing from the README?

**Comment by maurop123** [comment]
Any updates on this? I've got...

```
const Airtable = require('airtable')
const airtable = new Airtable.configure({ apiKey: 'APIKEY' })
console.log('airtable', airtable)
```

And am getting an empty object

```
{}
```

**Comment by EvanHahn** [comment]
I just followed the instructions on the README and successfully loaded the demo. Is it possible that you have an older demo on your machine? If so, could you tell us what steps brought you to this error? We'd love to help you debug it.

**Comment by maurop123** [comment]
So I just used the demo code to test. I replaced the code in the script tag of the index.html with this...
```
var Airtable = require('airtable');
var base = new Airtable({ apiKey: 'MY_API_KEY' }).base('MY_BASE_ID');
console.log('base', base)
base('Consume').select().eachPage(function page(records, fetchNextPage) {
    records.forEach(function(record) {
        console.log('Retrieved ', record);
    })
})
```
And I got this a `401 (Unauthorized)`

**Comment by EvanHahn** [comment]
Does your API key look like `keyJqskcyhPU0HzAR`?

**Comment by maurop123** [comment]
Yes, and today I found a typo in the key. I fixed it, and it started working in the in-browser demo.

Tried copy and pasting that script into an index.js and running with node, but no dice. Not sure what's wrong there.

**Comment by EvanHahn** [comment]
Sounds good! I'm going to close this but feel free to open a new issue if you have other problems.
