### ISSUE TITLE
How to access Lookup columns

### ISSUE THREAD

**Issue by bitliner** [Airtable/airtable.js#41]
If my record has a Lookup column, I struggle to get the related value using the client.

Example:

```
record.get('lookupColumnName') // is undefined
```

Version `0.5.1`

**Comment by syrnick** [comment]
Can you double-check that the record actually has value in there? If you go to the API docs and copy the Retrieve example for that table and use this record's ID, do you get the value of the lookup column?

If the checks above still point to an issue with airtable.js or the API, please email support (or file the issue from the UI). If you have a base you can share, that will help as well.

**Comment by bitliner** [comment]
@syrnick you right, I got the value from other records.
