### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by alecglassford** [Airtable/airtable.js#45]
Since you're providing this client and linking to it in the Airtable API documentation, I think we all presume you would like us to use it in our software! 😊 But it would be useful (legally, and to encourage everyone to use the software) to provide an explicit LICENSE.txt so we know our rights.

I see that https://github.com/Airtable/airtable-ruby is licensed under the MIT License. Perhaps that would be appropriate here as well?

Thanks so much for your work and for providing this great tool!

**Comment by kasrak** [comment]
Thanks, good call!
