### ISSUE TITLE
How to know when on last page of query

### ISSUE THREAD

**Issue by eorroe** [Airtable/airtable.js#49]
So I've written a wrapper for this library that I've been using for more than a year but need to add a method for fetching all records together

Heres what I have
```JS
let getAllDataFromTable = (table) => (filterQuery = {}) => {
  return new Promise((resolve, reject) => {
    let data = [];
    table.select(filterQuery)
     
    .eachPage((records, fetchNextPage) => {
      data = data.concat(records);
      fetchNextPage();
    });
  });
}
```

I'm not sure when to call `resolve(data)` because there's no way for me to know when on the last page. How come `fetchNextPage()` doesn't return anything or have a 3rd parameter to know when on the last page?

The documentation shows that `page` will be called or `done` will be called, is there any way to know what's about to be called?

![image](https://user-images.githubusercontent.com/6982605/36403137-eee3d0d4-15b0-11e8-8d13-2f70c6fc2702.png)

**Comment by kasrak** [comment]
Hi! There's actually already an `all()` method that hasn't been documented yet. I think you could use that: https://github.com/Airtable/airtable.js/blob/master/lib/query.js#L98

**Comment by eorroe** [comment]
Whoa thanks that will solve my rate limiting problem! 

But I also found the solution, I didn't realize that the second function was called when finished.

```JS
function done (error) {
 if (error) reject({ error });
 resolve(data);
}
```

The `if (err) ` part confused me and made me think that it was an error handler method

**Comment by kasrak** [comment]
Glad that helped :)

By the way, there's a little bug in your snippet above: if there's an error, it'll call `reject` and `resolve`. It can be avoided by adding moving the `resolve` inside an `else`.

**Comment by eorroe** [comment]
Nope, once resolved or rejected the other method won't be called, can't change a promise state. Not sure if there's a performance benefit (micro optimization IMO)

**Comment by kasrak** [comment]
You're right! Didn't know that about the Promise spec, thanks.
