### ISSUE TITLE
Rewrite library to be promised based

### ISSUE THREAD

**Issue by eorroe** [Airtable/airtable.js#50]
Any plans for this @kasrak ?

**Comment by kasrak** [comment]
We haven't had a chance to document this yet, but as of [v0.5.0](https://github.com/Airtable/airtable.js/releases/tag/v0.5.0) all of the methods that take a `done` callback will return a promise if you don't pass in a `done` callback.

E.g.

```js
table.select().firstPage(result => { ... })
```

is equivalent to

```js
table.select().firstPage().then(result => { ... })
```
