### ISSUE TITLE
Not sure how to set filterByFormula in API call

### ISSUE THREAD

**Issue by davidyeiser** [Airtable/airtable.js#51]
I can't figure out how `filterByFormula` values are supposed to be inputted.

My query for `select().eachPage()` looks like this:

    {
      pageSize: 50,
      sort: [{field: 'Publish Date', direction: 'desc'}]
    }

What I would like to do is filter by the field name of "Publish" to where only records that have "Publish" set as TRUE are returned. 

I tried this but it didn't like it:

    {
      pageSize: 50,
      filterByFormula: {Publish} = true,
      sort: [{field: 'Publish Date', direction: 'desc'}]
    }

I based that syntax off the example in the documentation: `NOT({Title} = '')`

I read through the documentation here:
https://support.airtable.com/hc/en-us/articles/203255215-Formula-field-reference

But I still couldn't figure out how to format the values.

**Comment by kasrak** [comment]
The value for `filterByFormula` should be a string. You can test the formula by creating a formula field from the Airtable UI.

```js
{
  pageSize: 50,
  filterByFormula: '{Publish} = TRUE()',
  sort: [{field: 'Publish Date', direction: 'desc'}]
}
```

**Comment by davidyeiser** [comment]
Thank you!
