### ISSUE TITLE
How do I use "err" without JSON.stringify()?

### ISSUE THREAD

**Issue by cparker4486** [Airtable/airtable.js#57]
Hello,

I'm a relative novice when it comes to JavaScript so forgive me if this question is very basic.

I'm trying to return the value `err` to the client but the string "Class " is being prepended to the output unless I do `JSON.stringify(err)`.

Here's what I see in my console:

![image](https://user-images.githubusercontent.com/1189638/39896202-079b0b20-5462-11e8-8a70-8742f7267cc9.png)

But here's what I see when I use `JSON.stringify(err)`:

    "{\"error\":\"INVALID_FILTER_BY_FORMULA\",\"message\":\"The formula for filtering records is invalid: please check your formula text.\",\"statusCode\":422}"

In this case, "Class " is nowhere to be found and I can return the response to the client without an issue. Where is "Class " coming from and how do I use `err` without `JSON.stringify()` first?

**Comment by EvanHahn** [comment]
`Class` is how Node chooses to log instances of `AirtableError`. You can see similar behavior by running the following Node script:

```javascript
class Person {
  constructor(first, last) {
    this.name = first + ' ' + last;
  }
}

const howie = new Person('Howie', 'Liu');
console.log(howie);  // Person { name: 'Howie Liu' }

const stringified = JSON.stringify(howie);
console.log(stringified);  // => {"name":"Howie Liu"}
```

This doesn't appear to be an issue with Airtable.js, so I'm going to close this issue. Feel free to follow up with more questions!
