### ISSUE TITLE
Update insecure dependency

### ISSUE THREAD

**Issue by mmazanec22** [Airtable/airtable.js#72]
GitHub notified me about an old version of hoek/cryptiles being in my package-lock.json.  I ran my repo through Snyk, and it looks like the insecure dependency was introduced via Airtable:

`Introduced through: community-network-mapping-server@1.0.0 › airtable@0.5.6 › request@2.85.0 › hawk@6.0.2 › cryptiles@3.1.2`

Thank you!

**Comment by EvanHahn** [comment]
Thanks for the report! I opened #73, which should hopefully fix your issue if it's merged.
