### ISSUE TITLE
Documentation for other clients

### ISSUE THREAD

**Issue by benoror** [Airtable/airtable.js#8]
It might be trivial but helpful to have some examples to consume the API from other platforms/languages, like in: https://github.com/fieldbook/api-docs/blob/master/client-examples.md 🙈

**Comment by gerardo-rodriguez** [comment]
+1 😉

**Comment by syrnick** [comment]
If you want to write an API client, feel free to send questions to support@airtable.com. We'll be happy to help. Looking through the source of the JS client might help - it should be somewhat easy to follow.

**Comment by benoror** [comment]
since opening this issue [airtable-ruby](https://github.com/Airtable/airtable-ruby) was added
